module.exports = {
  "rules": {
    "array-callback-return": 1,
    "block-scoped-var": 2,
    "curly": [2, "multi-line", "consistent"],
    "dot-location": [2, "property"],
    "dot-notation": [2, {"allowKeywords": true}],
    "eqeqeq": [2, "smart"],
    "guard-for-in": 1,
    "no-alert": 0,
    "no-case-declarations": 1,
    "no-div-regex": 1,
    "no-else-return": 1,
    "no-empty-function": 1,
    "no-empty-pattern": 2,
    "no-extra-bind": 2,
    "no-eval": 2,
    "no-fallthrough": 1,
    "no-implicit-globals": 2,
    "no-implied-eval": 2,
    "babel/no-invalid-this": 2,
    "no-iterator": 2,
    "no-labels": 2,
    "no-lone-blocks": 1,
    "no-loop-func": 2,
    "no-magic-numbers": [1, {"ignoreArrayIndexes": true, "ignore": [-1, 0, 1]}],
    "no-multi-spaces": 1,
    "no-multi-str": 2,
    "no-native-reassign": 2,
    "no-new": 1,
    "no-new-func": 2,
    "no-new-wrappers": 2,
    "no-param-reassign": [2, {"props": false}],
    "no-process-env": 1,
    "no-redeclare": [2, {"builtinGlobals": true}],
    "no-return-assign": 2,
    "no-self-assign": 2,
    "no-self-compare": 2,
    "no-throw-literal": 1,
    "no-unused-expressions": 1,
    "no-useless-call": 2,
    "no-useless-concat": 2,
    "no-with": 2,
    "radix": [2, "always"],
    "wrap-iife": [2, "outside"],
    "yoda": 2,
  }
}
